"""empty message

Revision ID: 16b46c0543a
Revises: 5900e63ab48
Create Date: 2015-01-11 18:41:18.837053

"""

# revision identifiers, used by Alembic.
revision = '16b46c0543a'
down_revision = '5900e63ab48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=True),
    sa.Column('leavable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['group_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('group_admin', sa.Boolean(), nullable=True),
    sa.Column('app_pending', sa.Boolean(), nullable=True),
    sa.Column('app_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_membership')
    op.drop_table('group')
    op.drop_table('group_category')
    ### end Alembic commands ###
