"""empty message

Revision ID: 2ecc9f25f6
Revises: 1904c391225
Create Date: 2015-01-05 09:50:39.642194

"""

# revision identifiers, used by Alembic.
revision = '2ecc9f25f6'
down_revision = '1904c391225'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
