"""empty message

Revision ID: 419aae7e9c5
Revises: 45336a5f97c
Create Date: 2015-01-12 18:16:24.719560

"""

# revision identifiers, used by Alembic.
revision = '419aae7e9c5'
down_revision = '45336a5f97c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_parent')
    ### end Alembic commands ###
