"""empty message

Revision ID: 45336a5f97c
Revises: 16b46c0543a
Create Date: 2015-01-12 18:08:55.957598

"""

# revision identifiers, used by Alembic.
revision = '45336a5f97c'
down_revision = '16b46c0543a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
