"""empty message

Revision ID: 5900e63ab48
Revises: 52cf5973de2
Create Date: 2015-01-06 11:15:35.153791

"""

# revision identifiers, used by Alembic.
revision = '5900e63ab48'
down_revision = '52cf5973de2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
